---
name: bump-build-number
on:
  push: #TODO remove before merging
  workflow_dispatch:
  schedule:
  - cron: '0 18 * * 5' # Run every Friday, at 6PM

permissions:
  contents: write
  pull-requests: write

jobs:
  bump-build-number:
    # This is required to run on MacOS
    runs-on: macos-12
    steps:
    - uses: mattermost/github-app-installation-token-action@181cd1b8c94b158428c4facfe043d6e28c20be55
      id: ghapp
      with:
        appId: "${{ vars.UNIFIED_CI_APP_ID }}"
        installationId: "${{ vars.UNIFIED_CI_INSTALLATION_ID }}"
        privateKey: ${{ secrets.UNIFIED_CI_PRIVATE_KEY }}

    - name: bump-build-number/checkout-repo
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      with:
        fetch-depth: 0

    - name: bump-build-number/setup-ruby
      uses: ruby/setup-ruby@8575951200e472d5f2d95c625da0c7bec8217c42 # v1.161.0
      with:
        ruby-version: "2.7"
        working-directory: fastlane
        bundler-cache: false

    - name: bump-build-number/bump-build-number
      env:
        GH_TOKEN: "${{ steps.ghapp.outputs.token }}"
        DRY_RUN: no
      run: ./scripts/bump_build_number.sh
...
